"""将sqlite数据库替换成mysql

Revision ID: 1170c4e97139
Revises: 
Create Date: 2026-03-30 18:40:21.066033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1170c4e97139'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户编号'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='用户密码'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='电子邮箱(选填)'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('bio', sa.String(length=255), nullable=True, comment='简介'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index('username_UNIQUE', 'user', ['username'], unique=True)
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='文章编号'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='浏览量'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_article_author_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='user_id'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='article_id'),
    sa.Column('comment', sa.Text(), nullable=False, comment='评论'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_comment_article_id_article')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_comment_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_index('fk_comment_article_idx', 'comment', ['article_id'], unique=False)
    op.create_index('fk_comment_user_idx', 'comment', ['user_id'], unique=False)
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False, comment='收藏id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章id'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_favorite_article_id_article')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_favorite_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite')),
    sa.UniqueConstraint('user_id', 'article_id', name='user_id_article_id_unique')
    )
    op.create_index('fk_favorite_article_idx', 'favorite', ['article_id'], unique=False)
    op.create_index('fk_favorite_user_idx', 'favorite', ['user_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章id'),
    sa.Column('viewed_at', sa.DateTime(), nullable=False, comment='浏览时间'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_history_article_id_article')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_history')),
    sa.UniqueConstraint('user_id', 'article_id', name='user_id_article_id_unique')
    )
    op.create_index('fk_history_article_idx', 'history', ['article_id'], unique=False)
    op.create_index('fk_history_user_idx', 'history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_history_user_idx', table_name='history')
    op.drop_index('fk_history_article_idx', table_name='history')
    op.drop_table('history')
    op.drop_index('fk_favorite_user_idx', table_name='favorite')
    op.drop_index('fk_favorite_article_idx', table_name='favorite')
    op.drop_table('favorite')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_index('fk_comment_user_idx', table_name='comment')
    op.drop_index('fk_comment_article_idx', table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_table('article')
    op.drop_index('username_UNIQUE', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
