"""给article的created_at添加了索引

Revision ID: 671e7388daa0
Revises: 1170c4e97139
Create Date: 2026-04-11 20:06:29.686451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671e7388daa0'
down_revision: Union[str, Sequence[str], None] = '1170c4e97139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_article_created_at'), 'article', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_created_at'), table_name='article')
    # ### end Alembic commands ###
