"""comment

Revision ID: 69b79a16dce0
Revises: e70768a67fe4
Create Date: 2026-03-25 16:40:04.885564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b79a16dce0'
down_revision: Union[str, Sequence[str], None] = 'e70768a67fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='user_id'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='article_id'),
    sa.Column('comment', sa.Text(), nullable=False, comment='评论'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_comment_article_id_article')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_comment_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index('fk_comment_article_idx', ['article_id'], unique=False)
        batch_op.create_index('fk_comment_user_idx', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_id'))
        batch_op.drop_index('fk_comment_user_idx')
        batch_op.drop_index('fk_comment_article_idx')

    op.drop_table('comment')
    # ### end Alembic commands ###
