"""add profile fields to user

Revision ID: 69f1d251cbe4
Revises: c63850cb1b8d
Create Date: 2026-03-20 18:03:12.993837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f1d251cbe4'
down_revision: Union[str, Sequence[str], None] = 'c63850cb1b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True, comment='性别'))
        batch_op.add_column(sa.Column('bio', sa.String(length=255), nullable=True, comment='简介'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('gender')
        batch_op.drop_column('nickname')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
