"""加入了浏览历史模块

Revision ID: b089a7fc6d74
Revises: 69b79a16dce0
Create Date: 2026-03-26 15:24:23.762841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b089a7fc6d74'
down_revision: Union[str, Sequence[str], None] = '69b79a16dce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ## commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章id'),
    sa.Column('viewed_at', sa.DateTime(), nullable=False, comment='浏览时间'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_history_article_id_article')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_history'))
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(),server_default='0', nullable=False, comment='浏览量'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    op.drop_table('history')
    # ### end Alembic commands ###
