"""给history加入了索引和联合唯一约束

Revision ID: e52e7b25f16a
Revises: b089a7fc6d74
Create Date: 2026-03-26 15:42:18.803887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52e7b25f16a'
down_revision: Union[str, Sequence[str], None] = 'b089a7fc6d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index('fk_hisory_article_idx', ['article_id'], unique=False)
        batch_op.create_index('fk_history_user_idx', ['user_id'], unique=False)
        batch_op.create_unique_constraint('user_id_article_id_unique', ['user_id', 'article_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_constraint('user_id_article_id_unique', type_='unique')
        batch_op.drop_index('fk_history_user_idx')
        batch_op.drop_index('fk_history_article_idx')

    # ### end Alembic commands ###
