"""add favorite table

Revision ID: e70768a67fe4
Revises: 810fe69c9561
Create Date: 2026-03-24 17:16:49.344394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70768a67fe4'
down_revision: Union[str, Sequence[str], None] = '810fe69c9561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False, comment='收藏id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章id'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_favorite_article_id_article')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_favorite_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite')),
    sa.UniqueConstraint('user_id', 'article_id', name='user_id_article_id_unique')
    )
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index('fk_favorite_article_idx', ['article_id'], unique=False)
        batch_op.create_index('fk_favorite_user_idx', ['user_id'], unique=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('username_UNIQUE', ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username_UNIQUE')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index('fk_favorite_user_idx')
        batch_op.drop_index('fk_favorite_article_idx')

    op.drop_table('favorite')
    # ### end Alembic commands ###
